# Generated by Django 4.1.7 on 2023-09-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotbooking_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewslot',
            name='time',
        ),
        migrations.AddField(
            model_name='interviewslot',
            name='time_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='interviewslot',
            name='time_start',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='interviewslot',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
