# Generated by Django 4.1.7 on 2023-09-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotbooking_app', '0002_remove_interviewslot_time_interviewslot_time_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewslot',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
