# Generated by Django 4.1.7 on 2023-09-30 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slotbooking_app', '0003_interviewslot_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewslot',
            name='email',
        ),
    ]
