# Generated by Django 4.1.7 on 2023-09-30 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slotbooking_app', '0005_meetinglink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetinglink',
            name='slot',
        ),
    ]
