# Generated by Django 4.1.7 on 2023-09-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotbooking_app', '0006_remove_meetinglink_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetinglink',
            name='link',
            field=models.TextField(null=True),
        ),
    ]
