# Generated by Django 4.1.7 on 2023-09-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotbooking_app', '0007_alter_meetinglink_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('date', models.DateField(null=True)),
                ('time_start', models.TimeField(null=True)),
                ('time_end', models.TimeField(null=True)),
            ],
        ),
    ]
