# Generated by Django 4.1.7 on 2023-09-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotbooking_app', '0008_bookedslots'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedslots',
            name='link',
            field=models.TextField(null=True),
        ),
    ]
