# Generated by Django 4.2.5 on 2023-10-02 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slotbooking_app', '0012_remove_meetinglink_user_alter_meetinglink_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetinglink',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='usermeetinglink',
            name='meeting_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='slotbooking_app.meetinglink'),
        ),
        migrations.AlterField(
            model_name='usermeetinglink',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
