# Generated by Django 4.2.5 on 2023-10-02 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slotbooking_app', '0013_alter_meetinglink_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinglink',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetinglink',
            name='link',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='UserMeetingLink',
        ),
    ]
