# Generated by Django 4.2.5 on 2023-10-02 05:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slotbooking_app', '0015_bookedslots_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookedSlots',
            new_name='BookedSlot',
        ),
    ]
